/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ISatiSwapable extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ISatiSwapable;
  clone(): ISatiSwapable;
  methods: {
    getAmountOfSatiFromPairedToken(
      _ERC20TokenAmount: number | string | BN
    ): NonPayableTransactionObject<string>;

    swapPairedTokenForSati(
      _ERC20TokenAmount: number | string | BN
    ): PayableTransactionObject<void>;

    getNumberOfPairedTokenFromSati(
      _satiAmount: number | string | BN
    ): NonPayableTransactionObject<string>;

    swapSatiForPairedToken(
      _satiAmount: number | string | BN
    ): PayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
