/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type Rate = ContractEventLog<{
  scaledPrice: string;
  timeStamp: string;
  0: string;
  1: string;
}>;
export type SwapRate = ContractEventLog<{
  exchangeType: string;
  sellingAmount: string;
  buyingAmount: string;
  0: string;
  1: string;
  2: string;
}>;
export type SwapTransfer = ContractEventLog<{
  beneficiary: string;
  amountSent: string;
  amountReceived: string;
  0: string;
  1: string;
  2: string;
}>;

export interface SatiEthSwap extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): SatiEthSwap;
  clone(): SatiEthSwap;
  methods: {
    getScaledRate(
      _scalingDecimal: number | string | BN
    ): NonPayableTransactionObject<string>;

    /**
     * Returns the address of the current owner.
     */
    owner(): NonPayableTransactionObject<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(): NonPayableTransactionObject<void>;

    satiToken(): NonPayableTransactionObject<string>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    getAmountOfSatiFromPairedToken(
      _weiAmount: number | string | BN
    ): NonPayableTransactionObject<string>;

    swapPairedTokenForSati(
      _ERC20TokenAmount: number | string | BN
    ): PayableTransactionObject<void>;

    getNumberOfPairedTokenFromSati(
      _satiAmount: number | string | BN
    ): NonPayableTransactionObject<string>;

    swapSatiForPairedToken(
      _satiTokenAmount: number | string | BN
    ): PayableTransactionObject<void>;
  };
  events: {
    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    Rate(cb?: Callback<Rate>): EventEmitter;
    Rate(options?: EventOptions, cb?: Callback<Rate>): EventEmitter;

    SwapRate(cb?: Callback<SwapRate>): EventEmitter;
    SwapRate(options?: EventOptions, cb?: Callback<SwapRate>): EventEmitter;

    SwapTransfer(cb?: Callback<SwapTransfer>): EventEmitter;
    SwapTransfer(
      options?: EventOptions,
      cb?: Callback<SwapTransfer>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "Rate", cb: Callback<Rate>): void;
  once(event: "Rate", options: EventOptions, cb: Callback<Rate>): void;

  once(event: "SwapRate", cb: Callback<SwapRate>): void;
  once(event: "SwapRate", options: EventOptions, cb: Callback<SwapRate>): void;

  once(event: "SwapTransfer", cb: Callback<SwapTransfer>): void;
  once(
    event: "SwapTransfer",
    options: EventOptions,
    cb: Callback<SwapTransfer>
  ): void;
}
