/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { CrowdsaleContract } from "./Crowdsale";
import { ERC20Contract } from "./ERC20";
import { EthSwapContract } from "./EthSwap";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { KYCValidationContract } from "./KYCValidation";
import { MigrationsContract } from "./Migrations";
import { MockV3AggregatorContract } from "./MockV3Aggregator";
import { OwnableContract } from "./Ownable";
import { RatableContract } from "./Ratable";
import { SatiEthSwapContract } from "./SatiEthSwap";
import { SatiTokenContract } from "./SatiToken";
import { SatiTokenSaleContract } from "./SatiTokenSale";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Crowdsale"): CrowdsaleContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "EthSwap"): EthSwapContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "KYCValidation"): KYCValidationContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "MockV3Aggregator"): MockV3AggregatorContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "Ratable"): RatableContract;
      require(name: "SatiEthSwap"): SatiEthSwapContract;
      require(name: "SatiToken"): SatiTokenContract;
      require(name: "SatiTokenSale"): SatiTokenSaleContract;
    }
  }
}

export { CrowdsaleContract, CrowdsaleInstance } from "./Crowdsale";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { EthSwapContract, EthSwapInstance } from "./EthSwap";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { KYCValidationContract, KYCValidationInstance } from "./KYCValidation";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  MockV3AggregatorContract,
  MockV3AggregatorInstance,
} from "./MockV3Aggregator";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { RatableContract, RatableInstance } from "./Ratable";
export { SatiEthSwapContract, SatiEthSwapInstance } from "./SatiEthSwap";
export { SatiTokenContract, SatiTokenInstance } from "./SatiToken";
export { SatiTokenSaleContract, SatiTokenSaleInstance } from "./SatiTokenSale";
