/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { AggregatorV3InterfaceContract } from "./AggregatorV3Interface";
import { CrowdsaleContract } from "./Crowdsale";
import { ERC20Contract } from "./ERC20";
import { ERC20BurnableContract } from "./ERC20Burnable";
import { ERC20PresetFixedSupplyContract } from "./ERC20PresetFixedSupply";
import { ERC20TokensSwapContract } from "./ERC20TokensSwap";
import { EthQuoteSwapContract } from "./EthQuoteSwap";
import { FaucetContract } from "./Faucet";
import { IERC20Contract } from "./IERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { ISwapableContract } from "./ISwapable";
import { KYCValidationContract } from "./KYCValidation";
import { MigrationsContract } from "./Migrations";
import { MockERC20TokenContract } from "./MockERC20Token";
import { MockV3AggregatorContract } from "./MockV3Aggregator";
import { OwnableContract } from "./Ownable";
import { RatableContract } from "./Ratable";
import { SatiTokenContract } from "./SatiToken";
import { SatiTokenSaleContract } from "./SatiTokenSale";
import { SwapableContract } from "./Swapable";
import { SwapContractFactoryContract } from "./SwapContractFactory";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AggregatorV3Interface"): AggregatorV3InterfaceContract;
      require(name: "Crowdsale"): CrowdsaleContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "ERC20Burnable"): ERC20BurnableContract;
      require(name: "ERC20PresetFixedSupply"): ERC20PresetFixedSupplyContract;
      require(name: "ERC20TokensSwap"): ERC20TokensSwapContract;
      require(name: "EthQuoteSwap"): EthQuoteSwapContract;
      require(name: "Faucet"): FaucetContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "ISwapable"): ISwapableContract;
      require(name: "KYCValidation"): KYCValidationContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "MockERC20Token"): MockERC20TokenContract;
      require(name: "MockV3Aggregator"): MockV3AggregatorContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "Ratable"): RatableContract;
      require(name: "SatiToken"): SatiTokenContract;
      require(name: "SatiTokenSale"): SatiTokenSaleContract;
      require(name: "Swapable"): SwapableContract;
      require(name: "SwapContractFactory"): SwapContractFactoryContract;
    }
  }
}

export {
  AggregatorV3InterfaceContract,
  AggregatorV3InterfaceInstance,
} from "./AggregatorV3Interface";
export { CrowdsaleContract, CrowdsaleInstance } from "./Crowdsale";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { ERC20BurnableContract, ERC20BurnableInstance } from "./ERC20Burnable";
export {
  ERC20PresetFixedSupplyContract,
  ERC20PresetFixedSupplyInstance,
} from "./ERC20PresetFixedSupply";
export {
  ERC20TokensSwapContract,
  ERC20TokensSwapInstance,
} from "./ERC20TokensSwap";
export { EthQuoteSwapContract, EthQuoteSwapInstance } from "./EthQuoteSwap";
export { FaucetContract, FaucetInstance } from "./Faucet";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { ISwapableContract, ISwapableInstance } from "./ISwapable";
export { KYCValidationContract, KYCValidationInstance } from "./KYCValidation";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  MockERC20TokenContract,
  MockERC20TokenInstance,
} from "./MockERC20Token";
export {
  MockV3AggregatorContract,
  MockV3AggregatorInstance,
} from "./MockV3Aggregator";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { RatableContract, RatableInstance } from "./Ratable";
export { SatiTokenContract, SatiTokenInstance } from "./SatiToken";
export { SatiTokenSaleContract, SatiTokenSaleInstance } from "./SatiTokenSale";
export { SwapableContract, SwapableInstance } from "./Swapable";
export {
  SwapContractFactoryContract,
  SwapContractFactoryInstance,
} from "./SwapContractFactory";
