/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface KYCValidationContract
  extends Truffle.Contract<KYCValidationInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<KYCValidationInstance>;
}

type AllEvents = never;

export interface KYCValidationInstance extends Truffle.ContractInstance {
  KYCCompletedRegistry(
    arg0: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  seKYCCompletedFor: {
    (_userAddress: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _userAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _userAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _userAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  seKYCRevokedFor: {
    (_userAddress: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _userAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _userAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _userAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  requireKYCCompletion(
    _buyer: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<void>;

  methods: {
    KYCCompletedRegistry(
      arg0: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    seKYCCompletedFor: {
      (_userAddress: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _userAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _userAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _userAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    seKYCRevokedFor: {
      (_userAddress: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _userAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _userAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _userAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    requireKYCCompletion(
      _buyer: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
